name: CRM Docker CI

on:
  push:
    branches:
      - main
      - master
      - develop
  pull_request:
    branches:
      - main
      - master
      - develop

jobs: #seção que define os trabalhos a serem executados
  docker-build: #nome do trabalho
    runs-on: ubuntu-latest #especifica o ambiente de execução do trabalho

    steps:
      - name: Checkout do código #baixa o código do repositório para o ambiente de execução
        uses: actions/checkout@v4

      - name: Configurar Docker Buildx #configura o ambiente para construção de imagens Docker
        uses: docker/setup-buildx-action@v3

      - name: Validar docker compose #verifica se o arquivo docker-compose.yml está correto
        run: docker compose config

      - name: Build backend #constrói a imagem Docker para o backend usando o Dockerfile localizado na pasta backend
        run: docker build -t crm-backend ./backend

      - name: Build frontend #constrói a imagem Docker para o frontend usando o Dockerfile localizado na pasta frontend
        run: docker build -t crm-frontend -f Dockerfile .

      - name: Subir containers para teste #inicia os containers definidos no docker-compose.yml para testar se estão funcionando corretamente
        run: docker compose up -d --build

      - name: Verificar containers ativos #exibe os containers que estão rodando para garantir que o backend e frontend foram iniciados corretamente
        run: docker compose ps

      - name: Exibir logs backend #exibe os logs do container do backend para verificar se está funcionando corretamente
        run: docker compose logs backend

      - name: Exibir logs frontend #exibe os logs do container do frontend para verificar se está funcionando corretamente
        run: docker compose logs frontend

      - name: Derrubar containers #finaliza os containers para liberar recursos, garantindo que o ambiente fique limpo para futuras execuções
        if: always()
        run: docker compose down # comando para parar e remover os containers, redes e volumes definidos no docker-compose.yml
